-- ==========================================
-- 1. CONFIGURACIÓN INICIAL Y TABLAS (DDL)
-- ==========================================

-- 1.1 Tabla de ROLES
CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL UNIQUE,
  descripcion TEXT
);

-- 1.2 Tabla de USUARIOS (Vinculada a auth.users de Supabase)
-- Nota: Usamos el ID de auth.users como llave primaria para sincronización perfecta
CREATE TABLE usuarios (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  nombre_completo VARCHAR(100),
  email VARCHAR(100),
  rol_id BIGINT REFERENCES roles(id) ON DELETE SET NULL,
  avatar_url TEXT,
  creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  actualizado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1.3 Tabla de GRUPOS (Clases o Equipos)
CREATE TABLE grupos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL, -- Ej: "4A Desarrollo", "Equipo Alfa"
  codigo_acceso VARCHAR(20) UNIQUE,
  creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1.4 Tabla Intermedia: MIEMBROS DEL GRUPO
CREATE TABLE miembros_grupo (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id UUID REFERENCES usuarios(id) ON DELETE CASCADE,
  grupo_id BIGINT REFERENCES grupos(id) ON DELETE CASCADE,
  fecha_union TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(usuario_id, grupo_id)
);

-- 1.5 Tabla de PROYECTOS
CREATE TABLE proyectos (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  descripcion TEXT,
  grupo_id BIGINT REFERENCES grupos(id) ON DELETE CASCADE,
  estado VARCHAR(20) DEFAULT 'Activo', -- Activo, Finalizado, Archivado
  creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  actualizado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1.6 Tabla de CRITERIOS (La Rúbrica)
CREATE TABLE criterios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(50) NOT NULL, -- Ej: "Funcionalidad", "UI/UX"
  descripcion TEXT,
  puntuacion_maxima INT DEFAULT 10
);

-- 1.7 Tabla de EVALUACIONES (Cabecera de la nota)
CREATE TABLE evaluaciones (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  proyecto_id UUID REFERENCES proyectos(id) ON DELETE CASCADE,
  evaluador_id UUID REFERENCES usuarios(id) ON DELETE SET NULL,
  calificacion_final DECIMAL(5,2) DEFAULT 0,
  fecha_evaluacion TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  actualizado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 1.8 Tabla de DETALLE DE EVALUACIONES (Desglose por criterio)
CREATE TABLE detalle_evaluaciones (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evaluacion_id UUID REFERENCES evaluaciones(id) ON DELETE CASCADE,
  criterio_id BIGINT REFERENCES criterios(id) ON DELETE RESTRICT,
  puntuacion_obtenida INT NOT NULL,
  UNIQUE(evaluacion_id, criterio_id) -- Un criterio solo se evalúa una vez por sesión
);

-- 1.9 Tabla de RETROALIMENTACIÓN (Comentarios)
CREATE TABLE retroalimentacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evaluacion_id UUID REFERENCES evaluaciones(id) ON DELETE CASCADE,
  comentario TEXT NOT NULL,
  es_publico BOOLEAN DEFAULT TRUE,
  creado_en TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==========================================
-- 2. FUNCIONES Y TRIGGERS (Automatización)
-- ==========================================

-- 2.1 Función para manejar 'updated_at' automáticamente
CREATE OR REPLACE FUNCTION handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.actualizado_en = timezone('utc'::text, now());
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger para Usuarios
CREATE TRIGGER on_update_usuarios
  BEFORE UPDATE ON usuarios FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();

-- Trigger para Proyectos
CREATE TRIGGER on_update_proyectos
  BEFORE UPDATE ON proyectos FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();

-- Trigger para Evaluaciones
CREATE TRIGGER on_update_evaluaciones
  BEFORE UPDATE ON evaluaciones FOR EACH ROW EXECUTE PROCEDURE handle_updated_at();

-- 2.2 Función para calcular la CALIFICACIÓN FINAL automáticamente
-- Suma los puntos del detalle y actualiza la tabla padre (evaluaciones)
CREATE OR REPLACE FUNCTION calcular_calificacion_total()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE evaluaciones
  SET calificacion_final = (
    SELECT COALESCE(SUM(puntuacion_obtenida), 0)
    FROM detalle_evaluaciones
    WHERE evaluacion_id = NEW.evaluacion_id -- Referencia al ID correcto tras Insert/Update
       OR evaluacion_id = OLD.evaluacion_id -- Referencia en caso de Delete
  )
  WHERE id = NEW.evaluacion_id OR id = OLD.evaluacion_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger que dispara el cálculo al mover los detalles
CREATE TRIGGER trigger_auto_calificacion
AFTER INSERT OR UPDATE OR DELETE ON detalle_evaluaciones
FOR EACH ROW
EXECUTE FUNCTION calcular_calificacion_total();

-- 2.3 Función Especial Supabase: Crear Usuario Público al Registrarse
-- Esto copia el usuario de auth.users a public.usuarios automáticamente
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.usuarios (id, email, nombre_completo)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger de Auth (Se ejecuta cada vez que alguien se registra en tu App)
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- ==========================================
-- 3. SEGURIDAD (ROW LEVEL SECURITY - RLS)
-- ==========================================

-- Habilitar RLS en todas las tablas
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE grupos ENABLE ROW LEVEL SECURITY;
ALTER TABLE miembros_grupo ENABLE ROW LEVEL SECURITY;
ALTER TABLE proyectos ENABLE ROW LEVEL SECURITY;
ALTER TABLE criterios ENABLE ROW LEVEL SECURITY;
ALTER TABLE evaluaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE detalle_evaluaciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE retroalimentacion ENABLE ROW LEVEL SECURITY;

-- Políticas Básicas (Ejemplos para arrancar)

-- ROLES: Lectura pública
CREATE POLICY "Roles son públicos" ON roles FOR SELECT USING (true);

-- CRITERIOS: Lectura pública
CREATE POLICY "Criterios son públicos" ON criterios FOR SELECT USING (true);

-- USUARIOS: Ver todos, editar solo el propio
CREATE POLICY "Ver perfiles" ON usuarios FOR SELECT USING (true);
CREATE POLICY "Editar propio perfil" ON usuarios FOR UPDATE USING (auth.uid() = id);

-- PROYECTOS: Ver proyectos si estás autenticado
CREATE POLICY "Ver proyectos autenticado" ON proyectos FOR SELECT TO authenticated USING (true);
-- (Aquí podrías agregar políticas para que solo 'Profesores' puedan crear/borrar)

-- ==========================================
-- 4. DATOS SEMILLA (Seed Data)
-- ==========================================

-- Insertar roles por defecto
INSERT INTO roles (nombre, descripcion) VALUES
('Administrador', 'Control total del sistema'),
('Profesor', 'Puede crear grupos y evaluar proyectos'),
('Alumno', 'Puede unirse a grupos y subir proyectos');

-- Insertar algunos criterios de ejemplo
INSERT INTO criterios (nombre, puntuacion_maxima) VALUES
('Funcionalidad', 10),
('Diseño UI/UX', 10),
('Calidad de Código', 10),
('Innovación', 5);
