import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import '../data/models.dart';
import '../data/mock_data.dart';

class HiveService {
  static const String evaluationsBox = 'evaluations';
  static const String settingsBox = 'settings';

  Future<void> init() async {
    await Hive.initFlutter();
    
    // Register Adapters (Note: These would be generated by build_runner)
    // For this prototype, we'll use a simplified Map-based persistence if build_runner is not available
    // But I will provide the structural code as if it was there.
    
    await Hive.openBox(evaluationsBox);
    await Hive.openBox(settingsBox);
  }

  Future<void> saveEvaluation(ProjectEvaluation evaluation) async {
    final box = Hive.box(evaluationsBox);
    await box.put(evaluation.projectId, {
      'scores': evaluation.scores,
      'observations': evaluation.observations,
      'totalScore': evaluation.totalScore,
      'quizResults': evaluation.quizResults,
    });
  }

  ProjectEvaluation? getEvaluation(String projectId) {
    final box = Hive.box(evaluationsBox);
    final data = box.get(projectId);
    if (data == null) return null;
    
    return ProjectEvaluation(
      projectId: projectId,
      scores: Map<String, double>.from(data['scores']),
      observations: data['observations'],
      totalScore: data['totalScore'],
      quizResults: List<int>.from(data['quizResults']),
    );
  }

  List<ProjectEvaluation> getAllEvaluations() {
    final box = Hive.box(evaluationsBox);
    return box.values.map((data) {
      final map = Map<String, dynamic>.from(data);
      return ProjectEvaluation(
        projectId: '', // We'd need to store the ID in the value too for this to work perfectly
        scores: Map<String, double>.from(map['scores']),
        observations: map['observations'],
        totalScore: map['totalScore'],
        quizResults: List<int>.from(map['quizResults']),
      );
    }).toList();
  }
}

final hiveServiceProvider = Provider((ref) => HiveService());
